platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa
use_frameworks!
workspace ‘SuperMovieiPhone.xcworkspace'

target :SuperMoiveiPhone do
    project ‘SuperMoiveiPhone/SuperMoiveiPhone.xcodeproj'
	pod 'SDWebImage'
	pod 'Reachability'
	pod 'JSONKit'
end
target :CCZCommonFramework do
    project ‘CCZCommonFramework/CCZCommonFramework.xcodeproj'
	pod 'JSONKit'
end
target :CCZDataModel do
    project ‘CCZDataModel/CCZDataModel.xcodeproj'
	pod 'JSONKit'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
